version: '3'
services:
  mission1:
    image: jupyter/base-notebook
    container_name: mission11-jupyter-notebook
    ports:
      - "9999:8888"
    volumes:
      - ./work:/home/jupyter/work/
    command: start-notebook.sh --NotebookApp.token=''
